# Generated by Django 4.0 on 2022-01-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('river_name', models.CharField(max_length=50)),
                ('river_description', models.TextField()),
                ('geojson', models.TextField()),
                ('get_in', models.DecimalField(decimal_places=6, max_digits=9)),
                ('get_out', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
