# Generated by Django 4.0 on 2023-01-07 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='get_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_ins', to='guidebook.place'),
        ),
        migrations.AddField(
            model_name='river',
            name='get_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_outs', to='guidebook.place'),
        ),
    ]
