# Generated by Django 4.0 on 2022-01-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='get_in',
        ),
        migrations.RemoveField(
            model_name='river',
            name='get_out',
        ),
        migrations.AddField(
            model_name='river',
            name='get_in_geojson',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='river',
            name='get_out_geojson',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
