# Generated by Django 4.0 on 2022-01-03 21:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0003_remove_river_geojson_remove_river_get_in_geojson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='get_in',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='river',
            name='get_out_geojson',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='river',
            name='river_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='river',
            name='river_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='river',
            name='route',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
