# Generated by Django 4.0 on 2022-01-04 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0004_river_get_in_river_get_out_geojson_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='river',
            old_name='get_out_geojson',
            new_name='get_out',
        ),
    ]
