# Generated by Django 4.0 on 2022-01-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0006_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
