# Generated by Django 4.0 on 2022-01-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0008_publiccomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AlterModelOptions(
            name='publiccomment',
            options={'ordering': ['-datetime_created']},
        ),
        migrations.AddField(
            model_name='river',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
