# Generated by Django 4.0 on 2022-02-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidebook', '0009_alter_note_options_alter_publiccomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='river',
            name='gauge_measure_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
